parameters:
    clusterpoint.class: Frontend\AppBundle\Clusterpoint\ClusterpointConnection

services:
    clusterpoint:
        class: %clusterpoint.class%
        arguments:
            - %cp_name%
            - %cp_password%
            - %cp_address%
            - %cp_id%
            - %cp_database%