common_app:
    resource: "@CommonAppBundle/Controller/"
    type:     annotation
    prefix:   /

backend_app:
    resource: "@BackendAppBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@BackendUserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@FrontendAppBundle/Controller/"
    type:     annotation
