parameters:
    clusterpoint.class: AppBundle\Clusterpoint\ClusterpointConnectionFactory

services:
    clusterpoint:
        class: %clusterpoint.class%
        arguments:
            - %cp_name%
            - %cp_password%
            - %cp_address%
            - %cp_id%